services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: app-ts
    volumes:
      - app-ts-data:/var/lib/postgres
    ports:
      - 8093:5432


  test_db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: test-app-ts
    volumes:
      - app-ts-test-data:/var/lib/postgres
    ports:
      - 8094:5432

volumes:
  app-ts-data:
  app-ts-test-data:
